 name: Java CI with Maven

on:
  push:
    branches: ["sub-master","pablo", "timothy"]
  pull_request:
    branches: ["sub-master","pablo", "timothy"]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build and Test with Maven
        run: mvn clean install
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          TEST_URL: ${{ secrets.TEST_URL }}
          FRONTEND_TEST_URL: ${{ secrets.FRONTEND_TEST_URL }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          USER_SIDE: ${{ secrets.USER_SIDE }}
